version: '3.5'
services:
  matrix:
    container_name: test-login
    image: node:latest
    command: bash -c 'cd /app && npm i && npm start'
    volumes:
      - ./:/app
    ports:
      - 8080:8080
